name: Build Windows EXE (Simple)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_gui.txt
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name=FileRenamer file_renamer_gui.py
        
    - name: Check file size
      run: |
        if (Test-Path "dist\FileRenamer.exe") {
          $size = (Get-Item "dist\FileRenamer.exe").Length / 1MB
          Write-Host "EXE file size: $([math]::Round($size, 2)) MB"
        }
        
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: FileRenamer-Windows-Simple
        path: dist/FileRenamer.exe
        retention-days: 30
