name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_gui.txt
        
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
        
    - name: Install UPX (for compression)
      run: |
        brew install upx
        
    - name: Build optimized App
      run: |
        # 使用优化的打包配置
        pyinstaller --onefile --windowed --name=FileRenamer \
          --clean --optimize=2 --strip --upx-dir=/usr/local/bin \
          --exclude-module=matplotlib --exclude-module=numpy \
          --exclude-module=pandas --exclude-module=scipy \
          --exclude-module=sklearn --exclude-module=tensorflow \
          --exclude-module=torch --exclude-module=onnxruntime \
          --exclude-module=cv2 --exclude-module=opencv \
          --exclude-module=rapidocr --exclude-module=tkinter \
          --exclude-module=wx --exclude-module=kivy \
          --exclude-module=IPython --exclude-module=jupyter \
          --exclude-module=notebook --exclude-module=sphinx \
          --exclude-module=docutils --exclude-module=pytest \
          --exclude-module=unittest --exclude-module=email \
          --exclude-module=http --exclude-module=urllib3 \
          --exclude-module=requests --exclude-module=sqlite3 \
          --exclude-module=xml --exclude-module=html \
          --exclude-module=xmlrpc --exclude-module=multiprocessing \
          --exclude-module=concurrent --exclude-module=asyncio \
          --exclude-module=logging --exclude-module=argparse \
          --exclude-module=getopt --exclude-module=doctest \
          --exclude-module=pdb --exclude-module=profile \
          --exclude-module=cProfile \
          --hidden-import=PyQt6.QtCore \
          --hidden-import=PyQt6.QtWidgets \
          --hidden-import=PyQt6.QtGui \
          --hidden-import=pytesseract \
          --hidden-import=pypdf \
          --hidden-import=docx \
          --hidden-import=chardet \
          --hidden-import=PIL \
          --hidden-import=PIL.Image \
          file_renamer_gui.py
          
    - name: Check file size
      run: |
        size=$(ls -lh dist/FileRenamer | awk '{print $5}')
        echo "App file size: $size"
        
        # Convert to MB for comparison
        size_mb=$(ls -l dist/FileRenamer | awk '{print $5}' | sed 's/[^0-9.]//g')
        if (( $(echo "$size_mb > 200" | bc -l) )); then
          echo "Warning: File size is larger than expected (>200MB)"
        else
          echo "Success: File size is within expected range"
        fi
        
    - name: Upload App artifact
      uses: actions/upload-artifact@v4
      with:
        name: FileRenamer-macOS
        path: dist/FileRenamer
        retention-days: 30
        
    - name: Create release info
      run: |
        version=$(date +"%Y.%m.%d")
        size=$(ls -lh dist/FileRenamer | awk '{print $5}')
        
        cat > release-notes-macos.md << EOF
        # FileRenamer macOS App
        
        **Build Date:** $version
        **File Size:** $size
        **Build Type:** Optimized (Stripped & Excluded unnecessary modules)
        
        ## Changes in this build:
        - Optimized dependencies and removed unused libraries
        - Excluded unnecessary Python modules (numpy, pandas, etc.)
        - Enabled PyInstaller optimizations (--strip, --optimize=2)
        - Enabled UPX compression for additional size reduction
        - Reduced file size significantly from ~500MB
        
        ## Installation:
        1. Download the App file
        2. Move to Applications folder (optional)
        3. Run directly (no installation required)
        
        ## System Requirements:
        - macOS 10.15+ (Catalina or later)
        - No additional Python installation required
        - Tesseract OCR engine (if using OCR features)
        EOF
        
    - name: Upload macOS release notes
      uses: actions/upload-artifact@v4
      with:
        name: Release-Notes-macOS
        path: release-notes-macos.md
        retention-days: 30
