name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.py'
      - 'requirements*.txt'
      - '.github/workflows/windows-build.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_gui.txt ]; then pip install -r requirements_gui.txt; fi
          pip install pyinstaller==6.15.0

      - name: Build with PyInstaller (onedir, windowed)
        shell: bash
        run: |
          pyinstaller \
            --onedir \
            --windowed \
            --name FileRenamer \
            --hidden-import=PyQt6.QtCore \
            --hidden-import=PyQt6.QtWidgets \
            --hidden-import=PyQt6.QtGui \
            --hidden-import=pytesseract \
            --hidden-import=pypdf \
            --hidden-import=docx \
            --hidden-import=chardet \
            --hidden-import=requests \
            --hidden-import=json \
            --hidden-import=pathlib \
            --hidden-import=shutil \
            --hidden-import=datetime \
            --hidden-import=re \
            --hidden-import=base64 \
            --hidden-import=PIL \
            --hidden-import=PIL.Image \
            --hidden-import=pdfplumber \
            file_renamer_gui.py

      - name: List dist contents
        shell: bash
        run: |
          ls -lah dist || true
          ls -lah dist/FileRenamer || true

      - name: Upload artifact (zip)
        if: ${{ always() }}
        shell: bash
        run: |
          cd dist
          7z a FileRenamer-windows.zip FileRenamer || powershell -Command "Compress-Archive -Path FileRenamer -DestinationPath FileRenamer-windows.zip -Force"
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileRenamer-windows
          path: |
            dist/FileRenamer-windows.zip
            dist/FileRenamer/**
          if-no-files-found: warn
